### ISSUE TITLE
[BUG] Versions 1.4.0 and 1.5.0 not updated on F-Droid

### ISSUE THREAD

**Issue by dutchgecko** [android-password-store/Android-Password-Store#648]
F-Droid lists 1.3.3 as the latest version: https://f-droid.org/packages/com.zeapo.pwdstore/

It seems the [build metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.zeapo.pwdstore.yml) is not up to date. I don't know if this file is maintained by this project, or whether someone from F-Droid keeps it up to date.

**Comment by msfjarvis** [comment]
AFAICT we're not the ones in charge of the F-Droid metadata. If someone wants to send them a PR with the new package name they're more than welcome to.

**Comment by hlavki** [comment]
Same on play store. Latest version is 1.3.2 from December 2018.

**Comment by msfjarvis** [comment]
> Same on play store. Latest version is 1.3.2 from December 2018.

You're looking at the wrong listing then. The README has an updated link that takes you to the active version.

**Comment by FabianHenneke** [comment]
I have "successfully" set up fdroidserver (https://gitlab.com/fdroid/fdroidserver/-/issues/756 should explain the quotes, it's been a bit of a wild ride) and built Password Store with it. Once I've become more familiar with the metadata language, we can submit a PR.

**Comment by FabianHenneke** [comment]
The following config provides a working F-Droid build. Main findings:

* We should ensure that for release tags tag name, version code and version name correspond to each other.
* F-Droid's auto update feature cannot deal with the split between `build.gradle` and `dependencies.gradle`. So either that split has to go or we will have to submit F-Droid PRs from time to time.

```yaml
Categories:
  - Internet
  - Science & Education
License: GPL-3.0-only
WebSite: https://github.com/android-password-store/Android-Password-Store/wiki
SourceCode: https://github.com/android-password-store/Android-Password-Store
IssueTracker: https://github.com/android-password-store/Android-Password-Store/issues
Translation: https://www.transifex.com/android-password-store/android-password-store/
Changelog: https://github.com/android-password-store/Android-Password-Store/releases

AutoName: Password Store
Description: |-
    Simple password manager that is compatible with [http://www.passwordstore.org/
    pass]: Passwords are stored in simple text files which are encrypted with
    OpenPGP.

    Requires [[org.sufficientlysecure.keychain]] to encrypt and decrypt passwords.

    '''Features:'''

    * Clone an existing pass repository
    * Initialize a new pass repository
    * List the passwords
    * Handle the directories as categories
    * Decrypt the password files (first line is the password, the rest is extra data)
    * Add a new password to the current category (or no category if added at the root)
    * Pull and Push changes to the remote repository
    * Ability to change remote repository info

RepoType: git
Repo: https://github.com/android-password-store/Android-Password-Store

Builds:
  - versionName: 1.7.0-SNAPSHOT
    versionCode: 10601
    commit: v1.6.0
    subdir: app
    gradle:
      - yes
    scandelete:
      - app/src/androidTest/assets/private_key
```
